version: '3'
services:
  app:
    image: node:18
    container_name: smart-talent-back
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm run start:dev
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=smart_talent_db

  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_talent_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
